dist: trusty
sudo: false
language: go

env:
  global:
    - DEP_VERSION="0.4.1"
before_install:
  # Download the binary to bin folder in $GOPATH
  - curl -L -s https://github.com/golang/dep/releases/download/v${DEP_VERSION}/dep-linux-amd64 -o $GOPATH/bin/dep
  # Make the binary executable
  - chmod +x $GOPATH/bin/dep
install:
# This script is used by the Travis build to install a cookie for
# go.googlesource.com so rate limits are higher when using `go get` to fetch
# packages that live there.
# See: https://github.com/golang/go/issues/12933
- bash scripts/gogetcookie.sh  
- go get -v github.com/codeclimate/test-reporter

before_script:
  - test-reporter before-build

script:
- make vet
- make test
- make testacc
- make vendor

after_script:
  - test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

branches:
  only:
  - master
matrix:
  include:
  - go: '1.11.x'
  - go: '1.12.x'
    env: 'TESTARGS="-coverprofile c.out"'
  fast_finish: true
  allow_failures:
  - go: tip
